import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
    title: 'Magis',
    description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}